### ISSUE TITLE
[FEATURE] Support for shell Nu

### ISSUE THREAD

**Issue by tversteeg** [tversteeg/emplace#10]
**What is the name of the shell you would like to see support for?**
Nu

**Comment by mborejdo** [comment]
Hey there! As there has been much progress on nushell's prompt and other features, like startup, aliases, etc, I am wondering, if you plan to revisit this issue.

**Comment by tversteeg** [comment]
Hi! I was not planning on revisiting this issue but since you are interested in it, I might, although a PR would also be greatly appreciated. I'm not sure how feasible supporting the Nu shell is, since there needs to be a way to execute the Emplace application whenever a command line entry is added.

**Comment by mborejdo** [comment]
hey there. thanks for reopening. adding something like this to my custom prompt, seems to work for now:
` emplace catch $(history | last);`

**Comment by tversteeg** [comment]
Thanks for the research! Support might be viable in that case.
Shells like Bash & ZSH also trigger Emplace whenever you open a new shell, unfortunately. So this is a known bug.

**Comment by tversteeg** [comment]
@all-contributors please add @mborejdo for ideas

**Comment by tversteeg** [comment]
@mborejdo Sorry for being so late, but I think I've fixed the support for the Nu shell. The only problem I have now is that the original prompt gets lost. Do you have any idea how to fix this?
