### ISSUE TITLE
[BUG] emplace install for scoop-packages fails

### ISSUE THREAD

**Issue by mborejdo** [tversteeg/emplace#106]
**Describe the bug**
Installing scoop-packages currently fails due to an incorrectly generated install-command `[ERROR] "sudo scoop install package": The system cannot find the file specified. (os error 2)`
returning `false` in scoop-mngrs  `needs_root` imlementation generates the correct command, but still scoop is not being found:
`[ERROR] "scoop install package": The system cannot find the file specified. (os error 2) `

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Shell: nushell

**Additional context**
the scoop command is not an executable, so maybe this is the problem here

**Comment by tversteeg** [comment]
This is pretty weird, what happens when you install something using scoop? Is it an alias? I have used scoop before with Git Bash on Windows.

**Comment by mborejdo** [comment]
Scoop works for me as expected on windows. On cmd, nushell, etc running `scoop list` does produce the expected output. Also emplace's `PackageInstalledMethod::Script(format!("scoop list | findstr {}", package))` returns the expected results. I am not using git-bash but mingit on windows. Unfortunately I dont have advanced knowledge on windows-command-execution internals :-)

**Comment by mborejdo** [comment]
Using this
```
    fn install_command(self) -> &'static str {
        "cmd /c scoop install"
    }
```

solves the problem for me. I am now able to install scoop packages via emplace.

**Comment by tversteeg** [comment]
Ah that's great, I'm wondering if that also works with scoop executables.

**Comment by mborejdo** [comment]
I have checked the latest scoop installation package and came across this
```
#!/bin/sh
powershell.exe -noprofile -ex unrestricted "C:\Users\user\scoop\apps\scoop\current\bin\scoop.ps1"  "$@"
``` 
this is a file named "scoop" in scoops shim-folder (being available in PATH) which was generated by the scoop installer.
So I think there is *no* scoop executable in the first place. Maybe, somehow (through git for windows bash stuff) it was not the CMD being called, but the extension-less "scoop" file, which got evaluated in gits bash somehow?

**Comment by tversteeg** [comment]
That makes a lot of sense, in that case I'm happy with the change you propose. Do you want to make a PR or do you want me to add it?

**Comment by mborejdo** [comment]
@tversteeg thats great. Go ahead and add it yourself. Will celebrate my first PR with something bigger :-)
