### ISSUE TITLE
[BUG] sub_commands matches inside package names

### ISSUE THREAD

**Issue by adamcstephens** [tversteeg/emplace#131]
**Describe the bug**
In #130 when attempting to add zypper support, I discovered that using the short form of install, `in`, the pattern will be removed from package names as well. I'm guessing a package with `install` in it would exhibit the same behavior.

**To Reproduce**
1. Check out #130
1. Attempt to install a package name that includes `in`. The tests do this as well.

**Expected behavior**
I'd expect `in` to match from the sub command, and the package names to not be modified.

**Desktop (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by tversteeg** [comment]
@all-contributors please add @adamcstephens for bug
