### ISSUE TITLE
[BUG] **History command not working**

### ISSUE THREAD

**Issue by ram02z** [tversteeg/emplace#140]
**Describe the bug**
Running the history command with the zsh and fish history file returns `[ERROR] Critical Emplace error while path to history file is not provided`

**To Reproduce**
1. emplace history /home/user/.zsh_history
2. or emplace history $HISTFILE

**Expected behavior**
Emplace to parse history file.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Shell: Fish

**Additional context**
I have tried against the fish history file as well. I am not sure if I am using the command right because the same error is always returned.

**Machine information**
#### Software version

emplace 0.4.1

#### Operating system

Linux 5.6.0-1036-oem

#### Command-line

```bash
emplace bugreport
```

#### Environment variables

```bash
SHELL=/usr/bin/fish
```

#### Git version

```
> git --version
git version 2.25.1
```

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

**Comment by tversteeg** [comment]
@all-contributors please add @ram02z for bug

**Comment by ram02z** [comment]
Thanks for the quick update.  The fix worked great!
