### ISSUE TITLE
[BUG] **Critical Emplace error while No such file or directory**

### ISSUE THREAD

**Issue by tversteeg** [tversteeg/emplace#154]
**Describe the bug**
Can't find directory when running it for the first time on an empty PC.

**To Reproduce**
1. Install Emplace
2. Add config to bashrc
3. Open new shell

**Expected behavior**

**Desktop:**
 - OS: Debian
 - Shell: Bash

**Machine information**

#### Software version

emplace 1.2.0

#### Operating system

Linux 5.10.0-3-amd64

#### Command-line

```bash
emplace bugreport 
```

#### Environment variables

```bash
SHELL=/bin/bash
```

#### Git version

Could not run command 'git': No such file or directory (os error 2)

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

**Comment by SilentVoid13** [comment]
Hello, I experience the same bug, just installed `emplace` using `cargo`.
Is there a quick fix ?

I discovered this project today and that's a really great idea ! 
I hope this will grow and get better and better.

**Comment by tversteeg** [comment]
@SilentVoid13 thanks for letting me know, it should be fixed in the latest version.
