### ISSUE TITLE
[BUG] **Package Manager name matching isn't working well.**

### ISSUE THREAD

**Issue by ModdedGamers** [tversteeg/emplace#156]
**Describe the bug**
If I install something using `bpkg`, emplace prompts to save the package using `pkg` as the package manager.

**To Reproduce**
1. Install `bpkg`.
2. Try to install term by doing `bpkg install term`.
3. 

**Expected behavior**
I expected `emplace` to not do anything

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.2
 - Shell: ZSH

**Additional context**
I'm working on adding `bpkg` support, but I can't add it without this bug being fixed.

**Machine information**
#### Software version

emplace 1.2.0

#### Operating system

Darwin 18.2.0

#### Command-line

```bash
emplace bugreport
```

#### Environment variables

```bash
SHELL=/bin/zsh
```

#### Git version

```
> git --version
git version 2.30.0
```

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

**Comment by tversteeg** [comment]
@all-contributors please add @ModdedGamers for bug
