### ISSUE TITLE
[FEATURE] emplace history bulk add

### ISSUE THREAD

**Issue by jayvdb** [tversteeg/emplace#165]
**Describe the bug**
I have started using emplace a few weeks after starting using a mac.   My history has some of the software I have installed and it would be great to quickly add most of the entries emplace can detect.

Multi-select might be a bit tricky, in which case I would use an option for emplace to bulk add automatically, and then I can manually remove the few which shouldnt be there.

**To Reproduce**
1. Do lots of `brew install`'s
2. Use `emplace history $HISTFILE`

**Expected behavior**
Multi-select or an `--all` flag

**Comment by tversteeg** [comment]
History already had a multi-select, it just had a different theme. I've made it consistent with `emplace install` now.
