### ISSUE TITLE
[BUG] Handle local cargo installs better

### ISSUE THREAD

**Issue by jayvdb** [tversteeg/emplace#169]
**Describe the bug**
Installing a path of `.` shouldnt be registered as '.'.

**To Reproduce**
```
cargo install --path .
  Installing emplace v1.3.1-alpha.0 (/Users/john.vandenberg/osx/emplace)
    Updating crates.io index
   Compiling libc v0.2.89
   Compiling proc-macro2 v1.0.24
....
    Replaced package `emplace v1.3.0` with `emplace v1.3.1-alpha.0 (/Users/john.vandenberg/osx/emplace)` (executable `emplace`)
Opening Emplace repo: "/Users/john.vandenberg/Library/Application Support/emplace".
Mirror this command?
- . (Cargo Rust)
[y/n]
```

**Expected behavior**
Dont try to register '.' as an installable, or expand `.` to be a complete path, and even better would be to determine the git repo and hash to make it reproducible.

**Desktop (please complete the following information):**
 - OS: mac
 - Shell: zsh

**Machine information**
#### Software version

emplace 1.3.1-alpha.0

#### Operating system

Darwin 20.3.0

#### Environment variables

```bash
SHELL=/usr/local/bin/zsh
EMPLACE_CONFIG='/Users/john.vandenberg/Library/Application Support/emplace.toml'
```

#### Git version

```
> git --version
git version 2.31.0
```

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

**Comment by jayvdb** [comment]
A more vague pip example found via history import:
```
[ ] requirements.txt (Python Pip)
```

There, the name `requirements.txt` could actually be a valid PyPI name, so simply doing heuristics on package name wouldnt suffice, however it would be a great first implementation.

**Comment by tversteeg** [comment]
I've added a heuristic that ignores packages that start with a special character. The `requirements.txt` for Python is a bit of a different case, I think I'll need to have a blacklist for each package manager for that.
