### ISSUE TITLE
[BUG] PyPi manager should ignore requirements*.{txt,pip,in}

### ISSUE THREAD

**Issue by jayvdb** [tversteeg/emplace#173]
Spawned from https://github.com/tversteeg/emplace/issues/169#issuecomment-801572869

**Describe the bug**
If the pip command is `-rfilename`, it should either be ignored, or its contents processed using a pip compliant parser and package names extracted.

Currently it will record an entry for package `requirements.txt`, which is not valid (c.f. https://pypi.org/project/requirements.txt/) , but it could be valid as that name complies with PyPI package name syntax.

**To Reproduce**
1. `echo foo > requirements.txt`
2. `pip install -r requirements.txt`

```
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement foo (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for foo (from -r requirements.txt (line 1))
Opening Emplace repo: "/Users/john.vandenberg/Library/Application Support/emplace".
Mirror this command?
- requirements.txt (Python Pip)
```

**Expected behavior**
Not add arguments to `-r` as a package name.

**Desktop (please complete the following information):**
 - OS: mac
 - Shell: zsh

**Machine information**
#### Software version

emplace 1.4.0

#### Operating system

Darwin 20.3.0

#### Environment variables

```bash
SHELL=/run/current-system/sw/bin/zsh
EMPLACE_CONFIG='/Users/john.vandenberg/Library/Application Support/emplace.toml'
```

#### Git version

```
> git --version
git version 2.31.0
```

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

**Comment by tversteeg** [comment]
Thanks for the report!
