### ISSUE TITLE
[BUG] emplace asks to mirror when starting a new shell while install in progress

### ISSUE THREAD

**Issue by jayvdb** [tversteeg/emplace#179]
**Describe the bug**
If an install is in progress in shell-1, creating a new shell will initiate the emplace mirror prompt in shell-2 before anything has been done.

**To Reproduce**
1. shell-1: brew install qt-creator # which takes a long time to download
2. open shell-2

**Expected behavior**
New shells should not prompt regarding actions started in a different shell

**Desktop (please complete the following information):**
 - OS: Linux
 - Shell: zsh

**Machine information**
#### Software version

emplace 1.4.0

#### Operating system

Darwin 20.3.0

#### Environment variables

```bash
SHELL=/run/current-system/sw/bin/zsh
EMPLACE_CONFIG='/Users/john.vandenberg/Library/Application Support/emplace.toml'
```

#### Git version

```
> git --version
git version 2.31.0
```

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

**Comment by jayvdb** [comment]
The prompt still appears in the original shell, even after 'n' was pressed to cancel the mirroring in the new shell.  So this issue is more of an annoyance than a 'data loss' situation.

**Comment by tversteeg** [comment]
Thanks for the report! Is it working as intended now?

**Comment by jayvdb** [comment]
That fixed it. Thx

**Comment by jayvdb** [comment]
Hmm, in zsh I think this is putting `# emplace` into my history buffer.

**Comment by tversteeg** [comment]
Yes that's how I fixed it, I don't know if there's another way to do it.

**Comment by jayvdb** [comment]
It is a less annoying problem than the original one you fixed, so we're going in the right direction. ;-)
