### ISSUE TITLE
[BUG] Capture brew tap invocation

### ISSUE THREAD

**Issue by jayvdb** [tversteeg/emplace#182]
**Describe the bug**
`brew install` depend on `brew tap`

**To Reproduce**
1. `brew tap foo`
2. `brew install something_from_foo`
3. On a different machine, sync the updates

**Expected behavior**
brew taps should be added to the db so that they can be re-run on another machine before any installs which depend on them.

**Desktop (please complete the following information):**
 - OS: macos
 - Shell: zsh

**Comment by tversteeg** [comment]
I don't feel that this is a bug since package manager sources are a bit outside of the scope of this application. In any case they are a feature request. Thanks for the report.

**Comment by jayvdb** [comment]
> In any case they are a feature request.

I didnt see an existing feature request about this.

Should I be creating a new issue that is a feature request?

**Comment by tversteeg** [comment]
Yeah that would be a good idea, thanks!
