### ISSUE TITLE
[FEATURE] Support for package manager RUA

### ISSUE THREAD

**Issue by j2ghz** [tversteeg/emplace#34]
**What is the name of the package manager you would like to see support for?**

https://github.com/vn971/rua#rua----

**What operating systems or derivative does this package manager support?**
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] BSD
- [ ] Redox
- [ ] iOS
- [ ] Android
- [ ] Other, namely:

**If Linux, is it only for a specific distro?**
- [x] Yes, namely: Arch-based distros
- [ ] No

**What type of package manager is this?**
- [ ] Programming language specific (e.g. Cargo for Rust)
- [x] General purpose (e.g. APT on Debian)
- [ ] Other, namely:

**Comment by tversteeg** [comment]
Hi, thanks for the feature request. I've created a new branch for this feature (`rua`). Could you test it for me? I can't test it myself since I'm not running an Arch setup. I'll be glad to help set you up for testing if you need help with that.

**Comment by j2ghz** [comment]
I have tested it, tried installing with `rua` and got the prompt to save, `emplace install` also works

**Comment by tversteeg** [comment]
@all-contributors please add @j2ghz for ideas
