### ISSUE TITLE
[FEATURE] Support for `cargo-binstall`

### ISSUE THREAD

**Issue by ololduck** [tversteeg/emplace#372]
**What is the name of the package manager you would like to see support for?**
[cargo-binstall](https://github.com/cargo-bins/cargo-binstall)

**What operating systems or derivative does this package manager support?**
- [x] Windows
- [x] Mac
- [x] Linux
- [ ] BSD
- [ ] Redox
- [ ] iOS
- [ ] Android
- [ ] Other, namely:

**If Linux, is it only for a specific distro?**
- [ ] Yes, namely:
- [x] No

**What type of package manager is this?**
- [x] Programming language specific (e.g. Cargo for Rust)
- [x] General purpose (e.g. APT on Debian)
- [ ] Other, namely:

**Are administrator priviliges required? (sudo, etc.)**
- [ ] Yes
- [x] No

**Comment by tversteeg** [comment]
Hi @ololduck, unfortunately I'm not maintaining this application anymore, so I won't pick up this issue. Any PR's are greatly appreciated though!

**Comment by ololduck** [comment]
Hi @tversteeg,

I tried to (and #340, while i'm at it) but i'm running into issues with `enum_dispatch`: it seems it can't differenciate between `PackageManager::from(Cargo)` & `PackageManager::from(CargoBinstall)`. The issue is solved if I put `CargoBinstall` on the line before `Cargo` in the `PackageManager` enum, but this make the cargo.rs tests fail...
Other than that, i must commend you for your architecture, it's surprisingly simple!

I will continue to try for a bit, but would appreciate any suggestion you might make.

**Comment by tversteeg** [comment]
That's very odd, what errors are you getting when you try to do that?

**Comment by ololduck** [comment]
Nevermind, I thought the error was with `enum_dispatch` but the error is actually from package_manager_impl.rs:from_line. it seems I must find a way to take into account subcommands.

**Comment by tversteeg** [comment]
You can practically copy the one for regular Cargo for this right?
