### ISSUE TITLE
[BUG] **emplace install**

### ISSUE THREAD

**Issue by 0xd34b33f** [tversteeg/emplace#71]
emplace install
16:00:49 [ INFO] No configuration file found.
The URL of the git repository you (want to) store the mirrors in:  link
   values must be emitted before tables
16:00:52 [ERROR] Critical Emplace error while installing packages

Caused by:
    values must be emitted before tables

**Comment by 0xd34b33f** [comment]
```
emplace install             
18:38:23 [ INFO] No configuration file found.
The URL of the git repository you (want to) store the mirrors in: https://github.com/0xd34b33f/emplace_storage.git
18:38:26 [ERROR] Critical Emplace error while installing packages

Caused by:
    values must be emitted before tables
```
Every config is empty, it's a first run on another host

**Comment by tversteeg** [comment]
So the repository isn't checked out?

**Comment by 0xd34b33f** [comment]
No

**Comment by tversteeg** [comment]
I tried to reproduce this on my machine, but no success. What are the contents of `.emplace` in the repository?

**Comment by tversteeg** [comment]
@0xd34b33f does #77 fix your issue?
