### ISSUE TITLE
[BUG] **cargo install false positive**

### ISSUE THREAD

**Issue by 0xd34b33f** [tversteeg/emplace#73]
cargo install --git https://github.com/buildfoundation/mainframer.git --branch 3.x 

```
Mirror these 2 commands?
- --git https://github.com/buildfoundation/mainframer.git (Cargo Rust)
- --git 3.x (Cargo Rust)
[Y/n] 
```

**Comment by tversteeg** [comment]
Thanks for the report! Do you want to mirror the branch as well or should it be ignored?

**Comment by 0xd34b33f** [comment]
Branch should be mirrored
