### ISSUE TITLE
[FEATURE] Support for package manager 

### ISSUE THREAD

**Issue by bensleveritt** [tversteeg/emplace#87]
**What is the name of the package manager you would like to see support for?**
Homebrew (https://brew.sh/)

**What operating systems or derivative does this package manager support?**
- [ ] Windows
- [x] Mac
- [x] Linux
- [ ] BSD
- [ ] Redox
- [ ] iOS
- [ ] Android
- [ ] Other, namely:

**If Linux, is it only for a specific distro?**
- [ ] Yes, namely:
- [ ] No

**What type of package manager is this?**
- [ ] Programming language specific (e.g. Cargo for Rust)
- [x] General purpose (e.g. APT on Debian)
- [ ] Other, namely:

**Are administrator priviliges required? (sudo, etc.)**
- [x] Yes
- [ ] No

**Comment by tversteeg** [comment]
Thanks for the request. I've implemented it as much as possible. Can you verify if everything works?

**Comment by bensleveritt** [comment]
Thanks for the quick response!

I've not used Emplace much yet, but the homebrew-bit seems to work (it catches installs). I can't seem to get the git side working, nor the `emplace history`, so it's hard to say what I'm doing wrong.

For example:

```
❯ emplace history ~/.zsh_history                                                                                                                                                                                                                          
20:37:30 [ERROR] Critical Emplace error while path to history file is not provided
```

Also, is it possible to set the config location to .config on macOS? I'd rather keep all my bits and peices together, and that's standard enough, even on macOS.

**Comment by tversteeg** [comment]
Ah I see how this might be confusing, you don't actually have to ever use the `emplace history` command. This is the only step that's required: https://github.com/tversteeg/emplace#zsh for ZSH.

For the config I've created issue #88.

**Comment by tversteeg** [comment]
@all-contributors please add @bensleveritt for ideas

**Comment by bensleveritt** [comment]
Ah ha, I had to use an existing repo that wasn't empty to get things moving. The error was asking me to check out master, but given that I'd used an empty repo Git complained and bailed.

Not sure how that repo should be initialised in the first instance, but for me just creating a master branch with a commit worked.

Happy to close now!
