### ISSUE TITLE
[FEATURE] Allow setting configuration file

### ISSUE THREAD

**Issue by tversteeg** [tversteeg/emplace#88]
There should be a global `-c` flag that allows you to set the location of the configuration file.

**Comment by bensleveritt** [comment]
It'd be great to set path during initialisation, maybe as part of the shell hook, or an environment variable that gets picked up?

**Comment by tversteeg** [comment]
@bensleveritt fixed this, you can now set the path with `emplace init -c PATH` in the shell configuration.
